import type { PersonaFixture } from "./types";

const JOB = "e-e-finlytics";
const INTERN = "e-e-kredible";
const PROJECT = "e-e-chatbot";
const BTECH = "e-e-btech";

export const engineer: PersonaFixture = {
  persona: "engineer",
  region: "IN",
  contact: {
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    phone: "+91 98450 67890",
    location: "Bengaluru, Karnataka",
    links: [{ label: "GitHub", url: "https://github.com/rahulverma-example" }],
  },
  describeText:
    "I'm a software engineer at Finlytics in Bengaluru since July 2023. I build Python FastAPI services for loan processing, added Redis caching to the loan-status API, and write pytest tests. Before that I interned at Kredible building React dashboards. I also built a chatbot that answers college questions from PDFs.",
  importText: [
    "RAHUL VERMA",
    "rahul.verma@example.com | +91 98450 67890 | github.com/rahulverma-example | Bengaluru",
    "EXPERIENCE",
    "Software Engineer, Finlytics, Bengaluru — Jul 2023 – Present",
    "- Built REST APIs in Python with FastAPI for the loan-processing service",
    "- Reduced p95 latency of the loan-status API from 900 ms to 350 ms by adding Redis caching",
    "- Wrote integration tests with pytest, raising coverage from 55% to 80%",
    "- Containerised two services with Docker for local development",
    "Software Engineering Intern, Kredible, Pune — May 2022 – Dec 2022",
    "- Built internal dashboards in React and TypeScript",
    "- Fixed 40+ bugs in the onboarding flow",
    "PROJECTS",
    "College helpdesk chatbot",
    "- Built a support chatbot that answers student queries from college PDFs using retrieval over embeddings",
    "- Used OpenAI embeddings and a FAISS index; deployed on Render",
    "EDUCATION",
    "B.Tech in Computer Science, VIT Vellore, 2019 – 2023",
    "SKILLS",
    "Python, FastAPI, PostgreSQL, Redis, Docker, React, TypeScript, Git, pytest",
  ].join("\n"),
  parse: {
    detectedLanguage: "English",
    canonicalRole: "Software Engineer",
    entries: [
      { id: JOB, kind: "job", title: "Software Engineer", org: "Finlytics", place: "Bengaluru", start: "2023-07", current: true },
      {
        id: INTERN,
        kind: "job",
        title: "Software Engineering Intern",
        org: "Kredible",
        place: "Pune",
        start: "2022-05",
        end: "2022-12",
        current: false,
      },
      { id: PROJECT, kind: "project", title: "College helpdesk chatbot", current: false },
      { id: BTECH, kind: "education", title: "B.Tech in Computer Science", org: "VIT Vellore", start: "2019", end: "2023", current: false },
    ],
    facts: [
      { id: "fe-apis", entryId: JOB, text: "Built REST APIs in Python with FastAPI for the loan-processing service", source: "upload" },
      {
        id: "fe-latency",
        entryId: JOB,
        text: "Reduced p95 latency of the loan-status API from 900 ms to 350 ms by adding Redis caching",
        source: "upload",
      },
      { id: "fe-tests", entryId: JOB, text: "Wrote integration tests with pytest, raising coverage from 55% to 80%", source: "upload" },
      { id: "fe-docker", entryId: JOB, text: "Containerised two services with Docker for local development", source: "upload" },
      { id: "fe-dash", entryId: INTERN, text: "Built internal dashboards in React and TypeScript", source: "upload" },
      { id: "fe-bugs", entryId: INTERN, text: "Fixed 40+ bugs in the onboarding flow", source: "upload" },
      {
        id: "fe-bot",
        entryId: PROJECT,
        text: "Built a support chatbot that answers student queries from college PDFs using retrieval over embeddings",
        source: "upload",
      },
      { id: "fe-faiss", entryId: PROJECT, text: "Used OpenAI embeddings and a FAISS index; deployed on Render", source: "upload" },
    ],
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "React", "TypeScript", "Git", "pytest"].map((name) => ({
      name,
      source: "fact" as const,
    })),
    languages: ["English", "Hindi"],
    rolePack: {
      role: "Software Engineer",
      region: "IN",
      duties: [
        "Code reviews",
        "Writing design docs",
        "On-call / production support",
        "Mentoring interns",
        "Setting up CI pipelines",
        "Writing unit and integration tests",
      ],
      skills: ["Python", "Java", "SQL", "Docker", "AWS", "Git", "System design"],
      certifications: ["AWS Certified Developer", "Google Cloud Associate"],
      questions: [
        { id: "q-scale", text: "Roughly what traffic or data size did your main service handle?", examples: ["~1k requests/min", "~1M rows", "Not sure"] },
        { id: "q-team", text: "How big was your team?", examples: ["3–5 people", "6–10 people"] },
      ],
      photoCommon: false,
    },
    questions: [
      { id: "q-scale", text: "Roughly what traffic or data size did the loan service handle?", examples: ["~1k requests/min", "~1M loans", "Not sure"], entryId: JOB },
      { id: "q-team", text: "How big was your team at Finlytics?", examples: ["3–5 people", "6–10 people"], entryId: JOB },
    ],
    suggestedDuties: [
      { text: "Code reviews", entryId: JOB },
      { text: "On-call / production support", entryId: JOB },
      { text: "Writing design docs", entryId: JOB },
      { text: "Mentoring interns", entryId: JOB },
    ],
  },
  answerToFact: {
    "q-scale": (a) => (/not sure/i.test(a) ? null : { text: `The loan service handled ${a}` }),
    "q-team": (a) => ({ text: `Worked in a team of ${a}` }),
  },
  sampleAnswers: {},
  sampleDuties: ["Code reviews"],
  factBullets: {
    "fe-latency": "Cut p95 latency of the loan-status API from 900 ms to 350 ms by adding Redis caching",
  },
  dutyBullets: {
    "Code reviews": "Review teammates' pull requests",
    "On-call / production support": "Share on-call duty for production services",
    "Writing design docs": "Write design docs for new services",
    "Mentoring interns": "Mentor interns on the team",
  },
  summary: {
    text: "Software engineer building Python and FastAPI services for loan processing at Finlytics, with a side project in retrieval-based chatbots.",
    factIds: ["fe-apis", "fe-bot"],
  },
  resumeTitle: "Software engineering resume",
  tailoring: {
    target: {
      company: "Nimbus Health",
      role: "AI Engineer",
      jdText:
        "Nimbus Health is hiring an AI Engineer in Bengaluru. You will build LLM-powered features for clinicians. Requirements: strong Python; experience building REST APIs with FastAPI or similar; hands-on experience with LLMs and retrieval-augmented generation (RAG); familiarity with vector databases such as FAISS or pgvector; Docker and CI/CD. Nice to have: LangGraph or other agent frameworks, AWS, and a habit of writing tests.",
    },
    requirements: [
      { id: "r1", text: "Strong Python", kind: "technical", priority: "must", origin: "generated", pinned: false, order: 0 },
      { id: "r2", text: "REST APIs with FastAPI or similar", kind: "technical", priority: "must", origin: "generated", pinned: false, order: 1 },
      { id: "r3", text: "LLMs and retrieval-augmented generation (RAG)", kind: "technical", priority: "must", origin: "generated", pinned: false, order: 2 },
      { id: "r4", text: "Vector databases (FAISS, pgvector)", kind: "technical", priority: "must", origin: "generated", pinned: false, order: 3 },
      { id: "r5", text: "Docker and CI/CD", kind: "technical", priority: "must", origin: "generated", pinned: false, order: 4 },
      { id: "r6", text: "LangGraph or other agent frameworks", kind: "technical", priority: "nice", origin: "generated", pinned: false, order: 5 },
      { id: "r7", text: "AWS", kind: "technical", priority: "nice", origin: "generated", pinned: false, order: 6 },
      { id: "r8", text: "Writing tests", kind: "technical", priority: "nice", origin: "generated", pinned: false, order: 7 },
    ],
    terms: [
      { term: "Python", requirementId: "r1", priority: "must" },
      { term: "FastAPI", requirementId: "r2", priority: "must" },
      { term: "REST", requirementId: "r2", priority: "must" },
      { term: "LLM", requirementId: "r3", priority: "must" },
      { term: "RAG", requirementId: "r3", priority: "must" },
      { term: "FAISS", requirementId: "r4", priority: "must" },
      { term: "Docker", requirementId: "r5", priority: "must" },
      { term: "CI/CD", requirementId: "r5", priority: "must" },
      { term: "LangGraph", requirementId: "r6", priority: "nice" },
      { term: "AWS", requirementId: "r7", priority: "nice" },
      { term: "pytest", requirementId: "r8", priority: "nice" },
    ],
    verdicts: [
      {
        requirementId: "r1",
        verdict: "covered",
        evidence: [{ quote: "Built REST APIs in Python with FastAPI for the loan-processing service", bulletId: "b-fe-apis" }],
      },
      {
        requirementId: "r2",
        verdict: "covered",
        evidence: [{ quote: "Built REST APIs in Python with FastAPI for the loan-processing service", bulletId: "b-fe-apis" }],
      },
      {
        requirementId: "r3",
        verdict: "partial",
        evidence: [{ quote: "answers student queries from college PDFs using retrieval over embeddings", bulletId: "b-fe-bot" }],
        note: "You've built retrieval, but the line never says RAG or LLM — the words recruiters search for.",
      },
      {
        requirementId: "r4",
        verdict: "partial",
        evidence: [{ quote: "Used OpenAI embeddings and a FAISS index", factId: "fe-faiss" }],
        note: "FAISS is in your facts but the resume line is easy to miss.",
      },
      {
        requirementId: "r5",
        verdict: "partial",
        evidence: [{ quote: "Containerised two services with Docker for local development", bulletId: "b-fe-docker" }],
        note: "Docker is covered; nothing about CI/CD.",
      },
      { requirementId: "r6", verdict: "missing", evidence: [] },
      { requirementId: "r7", verdict: "missing", evidence: [] },
      {
        requirementId: "r8",
        verdict: "covered",
        evidence: [{ quote: "Wrote integration tests with pytest, raising coverage from 55% to 80%", bulletId: "b-fe-tests" }],
      },
    ],
    proposals: [
      {
        id: "ep-1",
        requirementIds: ["r3"],
        change: {
          op: "replace",
          bulletId: "b-fe-bot",
          text: "Built a RAG chatbot that answers student queries from college PDFs using retrieval over embeddings",
          factIds: ["fe-bot"],
        },
        before: "Built a support chatbot that answers student queries from college PDFs using retrieval over embeddings",
      },
      {
        id: "ep-2",
        requirementIds: ["r4"],
        change: {
          op: "replace",
          bulletId: "b-fe-faiss",
          text: "Stored OpenAI embeddings in a FAISS index for retrieval; deployed the service on Render",
          factIds: ["fe-faiss"],
        },
        before: "Used OpenAI embeddings and a FAISS index; deployed on Render",
      },
      {
        id: "ep-3",
        requirementIds: ["r1", "r2"],
        change: {
          op: "replace",
          bulletId: "b-fe-apis",
          text: "Built REST APIs in Python (FastAPI) for the loan-processing service",
          factIds: ["fe-apis"],
        },
        before: "Built REST APIs in Python with FastAPI for the loan-processing service",
      },
    ],
    questions: [
      {
        id: "eg-cicd",
        requirementId: "r5",
        text: "The job asks for CI/CD. Have you set up or used a pipeline? Where?",
        examples: ["GitHub Actions at Finlytics", "GitLab CI", "Not yet"],
      },
      {
        id: "eg-langgraph",
        requirementId: "r6",
        text: "Have you used LangGraph or another agent framework? Where?",
        examples: ["In a side project", "Only tutorials", "Not yet"],
      },
      {
        id: "eg-aws",
        requirementId: "r7",
        text: "Have you deployed anything on AWS? What and where?",
        examples: ["Lambda at Finlytics", "EC2 for a side project", "Not yet"],
      },
    ],
    gapEntryId: JOB,
  },
  market: {
    status: "ready",
    role: "AI Engineer",
    region: "IN",
    postingCount: 20,
    fetchedAt: "2026-09-28T09:00:00.000Z",
    terms: [
      { term: "Python", count: 18, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-1"] },
      { term: "LLM", count: 15, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-2"] },
      { term: "SQL", count: 13, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-3"] },
      { term: "Docker", count: 12, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-4"] },
      { term: "RAG", count: 11, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-5"] },
      { term: "AWS", count: 10, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-6"] },
      { term: "FastAPI", count: 9, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-7"] },
      { term: "Vector database", count: 9, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-8"] },
      { term: "PyTorch", count: 8, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-9"] },
      { term: "LangGraph", count: 7, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-10"] },
      { term: "Kubernetes", count: 6, kind: "technical", sampleUrls: ["https://example.com/jobs/ai-11"] },
    ],
  },
};
